[profile.default]
src = "src"
out = "out"
libs = ["lib"]
viaIR = true # a temporary solution to enable IR because of stack too deep error
remappings = [
    "@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/",
    "@openzeppelin/=lib/openzeppelin-contracts/",
    "forge-std/=lib/forge-std/src/"
]

[profile.monad]
src = "src"
out = "out"
libs = ["lib"]
remappings = [
    "@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/",
    "@openzeppelin/=lib/openzeppelin-contracts/",
    "forge-std/=lib/forge-std/src/"
]

metadata = true
metadata_hash = "none"  # disable ipfs
use_literal_content = true # use source code

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options

[rpc_endpoints]
localhost = "${LOCALHOST_RPC_URL}"
monad-testnet = "${MONADTESTNET_RPC_URL}"

[etherscan]
mainnet = { key = "${ETH_API_KEY}", url = "https://etherscan.io" }
monad-testnet = { key = "${ETH_API_KEY}", url = "https://testnet.monadexplorer.com" }
